Create proper issue text if Rust compilation fails

diff --git a/.github/workflows/scheduled.yaml b/.github/workflows/scheduled.yaml
--- a/.github/workflows/scheduled.yaml
+++ b/.github/workflows/scheduled.yaml
@@ -11,18 +11,19 @@ jobs:
     permissions:
       issues: write
     steps:
-      - id: build-beta
+      - uses: actions/checkout@v4
+      - run: rustup update beta && rustup default beta
+      - name: Compile the code with the beta compiler
+        id: build-beta
         run: |
           set -uex
-          echo 'some script, that runs for some time'
-          sleep 30
-          if [ "$(( "$(date +%M)" & 1 ))" -eq 0 ]; then
-            echo 'Oh no, the build failed!' > error.log
+          if ! cargo run > error.log 2>&1; then
             echo "compiler-output=$(cat error.log)" >> $GITHUB_OUTPUT
             false
           fi
       # https://docs.github.com/en/actions/use-cases-and-examples/project-management/scheduling-issue-creation
-      - run: gh issue create --title "Test Issue created by periodic Workflow" --body "This was created on $(date) due to the following error:\n${{steps.build-beta.outputs.compiler-output}}"
+      - name: Create an issue, since the beta-build is broken
+        run: printf 'Hello, I have detected, that this repository does not work with the current beta compiler.\n\nIt looks like, there were changes introduced, that broke this repository. Please take actions to fix this before the behavior reaches stable. The error was:\n```console\n%s\n```' "${{steps.build-beta.outputs.compiler-output}}" | gh issue create --title 'The compilation fails with current beta compiler' --body-file -
         if: ${{ failure() }}
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
